### PR TITLE
Fix built-in DAC mode

### PR DESCRIPTION
**Pull request by supersat**
See https://www.esp32.com/viewtopic.php?p=7670&sid=be41ebc8f1ef401a79f82073a73eaad2#p7629 for discussion.

### CODE REVIEW

**Comment by supersat** [comment]
Fixes issue #1

**Comment by MrBuddyCasino** [comment]
Thanks! Not sure I get the "+ 0x80" part, can you elaborate?

**Comment by supersat** [comment]
The left shift by 8 reduces the sample range to -0x80 to +0x7f. Adding 0x80 shifts this range to be between 0x00 and 0xff, which is what the built-in DAC expects. If you want to think about it in analog terms, it's adding a DC bias to the AC signal to keep it positive at all times.

**Comment by MrBuddyCasino** [comment]
I see - that means that the samples produced by MAD are signed, right?

**Comment by supersat** [comment]
I believe so.

**Pull request merged**
