### PR TITLE
[mad] (re)add layer I, II support as used by certain satellite feeds....

### PR DESCRIPTION
**Pull request by langer-michael**
… This also fixes an unhandled exception in case MPG I or II streams are fed into the ESP.

### CODE REVIEW

**Comment by MrBuddyCasino** [comment]
Thanks! Got a URL to test it with?

**Comment by langer-michael** [comment]
Sorry, but not one that is accessible from the internet.

The stream I use is from my local network, provided by a vdr streamdev instance.

**Comment by MrBuddyCasino** [comment]
I'll find something. Amazed to get a response at what must be late at night / very eraly in the morning in Canada.

**Comment by langer-michael** [comment]
Canada? No, it's more likely Germany ;-).

**Comment by MrBuddyCasino** [comment]
Damn. I took a chance - and lost. 
Guess you're not this guy: http://www.cim.mcgill.ca/~langer/

**Comment by langer-michael** [comment]
Right, this guy looks smarter than me.

**Pull request merged**
